[package]
name = "run"
version = "0.4.1"
authors = ["Jack Mordaunt <jackmordaunt@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"

[dev-dependencies]
pretty_assertions = "0.6.1"